"""Add reset_code and reset_code_expire to User

Revision ID: 12dead9c0645
Revises: f53d15497e42
Create Date: 2025-06-28 02:25:10.354239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dead9c0645'
down_revision = 'f53d15497e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expire', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expire')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
